name: food_stuff
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  freezed: ^2.5.2
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.4.1
  flutter_html: ^3.0.0-alpha.3
  shared_preferences: ^2.2.3
  url_strategy: ^0.2.0
  cached_network_image: ^3.3.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.1.5

flutter:
  uses-material-design: true

  assets:
  - assets/image/
